### ISSUE TITLE
Is there any chance to access the pert-trained model? 

### ISSUE THREAD

**Issue by roimulia2** [diegovalsesia/piunet#1]
Hey there!

Is there any chance to access the pert-trained model? 

Roi

**Comment by diegovalsesia** [comment]
Hi, yes I will post the pretrained models along with the rest of the code soon.

**Comment by roimulia2** [comment]
Thanks! Waiitng

**Comment by diegovalsesia** [comment]
Hi! Links to the pretrained models are now available along with the full code. Sorry for the delay!
