### ISSUE TITLE
validation dataset

### ISSUE THREAD

**Issue by SuzannaLin** [diegovalsesia/piunet#2]
Hello! Thank you for sharing your network!

Do you have a specific script for splitting the training data into 'train' and 'val'?

**Comment by diegovalsesia** [comment]
Hi, thanks for you question, there was an issue in our instructions.

There is a standard train/val partition that is required by the preprocessing notebook. We fixed the instructions in the readme to add a link to download the partitioned data (https://www.dropbox.com/s/0724byclle90nhg/probav_data.zip?dl=0).

**Comment by SuzannaLin** [comment]
I got it. Thank you!
