### ISSUE TITLE
Save_dataset_pickles.ipynb

### ISSUE THREAD

**Issue by SuzannaLin** [diegovalsesia/piunet#4]
In the readme, you refer to the script Save_dataset_pickles.ipynb
Is this the same one as in the DeepSum repo? What does this script do exactly?
Thank you for your help!

**Comment by diegovalsesia** [comment]
It was a leftover from DeepSUM, it is not needed and we removed it from the instructions.

**Comment by SuzannaLin** [comment]
Thanks!
